# Schema Configuration for sys-bio-kgs
# Using Systems Biology Ontology (SBO) as the head ontology
# SBO URL: https://raw.githubusercontent.com/EBI-BioModels/SBO/refs/heads/master/SBO_OWL.owl

# SBGN and SBML biochemical reaction components mapped to SBO classes
# Using SBO classes directly where they exist (no is_a if class exists in SBO)


# so that all children have name, sbo, notes, annotations
occurring entity representation: # SBO_0000231: occurring entity representation
  represented_as: node
  properties:
    name: string
    sbo: string

    notes_base64: string
    notes: string

    # qualifierss from momapy
    encodes: list[string]
    hasPart: list[string]
    hasProperty: list[string]
    hasVersion: list[string]
    is: list[string]
    isDescribedBy: list[string]
    isEncodedBy: list[string]
    isHomologTo: list[string]
    isPartOf: list[string]
    isPropertyOf: list[string]
    isVersionOf: list[string]
    occursIn: list[string]
    hasTaxon: list[string]
    hasInstance: list[string]
    is: list[string]
    isDerivedFrom: list[string]
    isDescribedBy: list[string]
    isInstanceOf: list[string]

model:
  is_a: occurring entity representation # SBO_0000231: occurring entity representation
  represented_as: node
  input_label: model

  properties:
    name: string
    sbo: string

    notes_base64: string
    notes: string

    # qualifierss from momapy
    encodes: list[string]
    hasPart: list[string]
    hasProperty: list[string]
    hasVersion: list[string]
    is: list[string]
    isDescribedBy: list[string]
    isEncodedBy: list[string]
    isHomologTo: list[string]
    isPartOf: list[string]
    isPropertyOf: list[string]
    isVersionOf: list[string]
    occursIn: list[string]
    hasTaxon: list[string]
    hasInstance: list[string]
    is: list[string]
    isDerivedFrom: list[string]
    isDescribedBy: list[string]
    isInstanceOf: list[string]

    # OPTIONAL (add later if needed)
    #num_compartments: int
    #num_species: int
    #num_reactions: int
    #num_genes: int

# SBML - species, SBGN - entity pool
physical entity representation: # SBO_0000236: physical entity representation
  represented_as: node
  inherit_properties: true
  input_label: entity

  properties:
    name: string
    sbo: string

    notes_base64: string
    notes: string

    # qualifierss from momapy
    encodes: list[string]
    hasPart: list[string]
    hasProperty: list[string]
    hasVersion: list[string]
    is: list[string]
    isDescribedBy: list[string]
    isEncodedBy: list[string]
    isHomologTo: list[string]
    isPartOf: list[string]
    isPropertyOf: list[string]
    isVersionOf: list[string]
    occursIn: list[string]
    hasTaxon: list[string]
    hasInstance: list[string]
    is: list[string]
    isDerivedFrom: list[string]
    isDescribedBy: list[string]
    isInstanceOf: list[string]

# SBML - reaction, SBGN - process
process: # SBO_0000375: process
  represented_as: node
  inherit_properties: true
  input_label: process

  properties:
    name: string
    sbo: string

    notes_base64: string
    notes: string

    # qualifierss from momapy
    encodes: list[string]
    hasPart: list[string]
    hasProperty: list[string]
    hasVersion: list[string]
    is: list[string]
    isDescribedBy: list[string]
    isEncodedBy: list[string]
    isHomologTo: list[string]
    isPartOf: list[string]
    isPropertyOf: list[string]
    isVersionOf: list[string]
    occursIn: list[string]
    hasTaxon: list[string]
    hasInstance: list[string]
    is: list[string]
    isDerivedFrom: list[string]
    isDescribedBy: list[string]
    isInstanceOf: list[string]

    # OPTIONAL (add later if needed)
    #reversible: bool               # reaction.reversible
    #lower_flux_bound: float        # reaction.lower_flux_bound
    #upper_flux_bound: float        # reaction.upper_flux_bound
    #gpr: string                    # reaction.safe_gpr_string()


# SBML - compartment, SBGN - compartment
physical compartment: # SBO_0000290: compartment
  represented_as: node
  inherit_properties: true
  input_label: compartment

  properties:
    name: string
    sbo: string

    notes_base64: string
    notes: string

    # qualifierss from momapy
    encodes: list[string]
    hasPart: list[string]
    hasProperty: list[string]
    hasVersion: list[string]
    is: list[string]
    isDescribedBy: list[string]
    isEncodedBy: list[string]
    isHomologTo: list[string]
    isPartOf: list[string]
    isPropertyOf: list[string]
    isVersionOf: list[string]
    occursIn: list[string]
    hasTaxon: list[string]
    hasInstance: list[string]
    is: list[string]
    isDerivedFrom: list[string]
    isDescribedBy: list[string]
    isInstanceOf: list[string]

# SBML - speciesReference/reactant, SBGN - consumption arc
reactant: # SBO_0000010: reactant
  represented_as: edge
  inherit_properties: true
  input_label: reactant
  properties:
    stoichiometry: float

    name: string
    sbo: string

    notes_base64: string
    notes: string

    # qualifierss from momapy
    encodes: list[string]
    hasPart: list[string]
    hasProperty: list[string]
    hasVersion: list[string]
    is: list[string]
    isDescribedBy: list[string]
    isEncodedBy: list[string]
    isHomologTo: list[string]
    isPartOf: list[string]
    isPropertyOf: list[string]
    isVersionOf: list[string]
    occursIn: list[string]
    hasTaxon: list[string]
    hasInstance: list[string]
    is: list[string]
    isDerivedFrom: list[string]
    isDescribedBy: list[string]
    isInstanceOf: list[string]

# SBML - speciesReference/product, SBGN - production arc
product: # SBO_0000011: product
  represented_as: edge
  inherit_properties: true
  input_label: product
  properties:
    stoichiometry: float

    name: string
    sbo: string

    notes_base64: string
    notes: string

    # qualifierss from momapy
    encodes: list[string]
    hasPart: list[string]
    hasProperty: list[string]
    hasVersion: list[string]
    is: list[string]
    isDescribedBy: list[string]
    isEncodedBy: list[string]
    isHomologTo: list[string]
    isPartOf: list[string]
    isPropertyOf: list[string]
    isVersionOf: list[string]
    occursIn: list[string]
    hasTaxon: list[string]
    hasInstance: list[string]
    is: list[string]
    isDerivedFrom: list[string]
    isDescribedBy: list[string]
    isInstanceOf: list[string]


# SBML - modifierSpeciesReference, SBGN - modifier arc
modifier: # SBO_0000019: modifier
  represented_as: edge
  inherit_properties: true
  input_label: modifier

  properties:
    name: string
    sbo: string

    notes_base64: string
    notes: string

    # qualifierss from momapy
    encodes: list[string]
    hasPart: list[string]
    hasProperty: list[string]
    hasVersion: list[string]
    is: list[string]
    isDescribedBy: list[string]
    isEncodedBy: list[string]
    isHomologTo: list[string]
    isPartOf: list[string]
    isPropertyOf: list[string]
    isVersionOf: list[string]
    occursIn: list[string]
    hasTaxon: list[string]
    hasInstance: list[string]
    is: list[string]
    isDerivedFrom: list[string]
    isDescribedBy: list[string]
    isInstanceOf: list[string]


# SBML and SBGN: localisation in a compartment
contained entity: # SBO_0000664
  represented_as: edge
  inherit_properties: true
  input_label: contained entity

  properties:
    name: string
    sbo: string
    notes_base64: string
    notes: string

    # qualifierss from momapy
    encodes: list[string]
    hasPart: list[string]
    hasProperty: list[string]
    hasVersion: list[string]
    is: list[string]
    isDescribedBy: list[string]
    isEncodedBy: list[string]
    isHomologTo: list[string]
    isPartOf: list[string]
    isPropertyOf: list[string]
    isVersionOf: list[string]
    occursIn: list[string]
    hasTaxon: list[string]
    hasInstance: list[string]
    is: list[string]
    isDerivedFrom: list[string]
    isDescribedBy: list[string]
    isInstanceOf: list[string]

# edges from model to its components
is a entity of:
  is_a: participant # SBO_0000235
  represented_as: edge
  input_label: entity_of
  target: model
  source: physical entity representation

is a process of:
  is_a: participant # SBO_0000235
  represented_as: edge
  input_label: process_of
  target: model
  source: process

is a compartment of:
  is_a: participant # SBO_0000235
  represented_as: edge
  input_label: compartment_of
  target: model
  source: physical compartment

# --------------------------- GEM Stuff ---------------------------

gene: # SBO_0000243: gene
  represented_as: node
  input_label: gene
  properties:
    name: string
    sbo: string

    notes_base64: string
    notes: string

    # qualifierss from momapy
    encodes: list[string]
    hasPart: list[string]
    hasProperty: list[string]
    hasVersion: list[string]
    is: list[string]
    isDescribedBy: list[string]
    isEncodedBy: list[string]
    isHomologTo: list[string]
    isPartOf: list[string]
    isPropertyOf: list[string]
    isVersionOf: list[string]
    occursIn: list[string]
    hasTaxon: list[string]
    hasInstance: list[string]
    is: list[string]
    isDerivedFrom: list[string]
    isDescribedBy: list[string]
    isInstanceOf: list[string]

gene-reaction association:
  represented_as: edge
  input_label: gene-reaction
  properties:
    rule_fragment: string # gpr rule